server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meisam?useSSL=false
    username: postgres
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

  security:
    user:
      name: meisam
      password: 1234
  rabbitmq:
    dynamic: true
    host: localhost
    port: 5672

papi:
  uri: http://dummy.restapiexample.com/api/v1/employees

redisson:
  url: redis://127.0.0.1:6379

rabbitapi:
  queue: hello
